# 关键点索引
LEFT_PUPIL_INDEX = 468
RIGHT_PUPIL_INDEX = 473
LEFT_IRIS_INDICES = [469, 470, 471, 472]
RIGHT_IRIS_INDICES = [474, 475, 476, 477]

# 状态码
STATUS_SUCCESS = 0
STATUS_NO_FACE_DETECTED = 1
STATUS_LOW_CONFIDENCE = 2
STATUS_INVALID_DEPTH = 3

# 相机参数相关常量
DEFAULT_CAMERA_PARAMS_FILE = "config/camera_params.json"
CAMERA_PARAMS_REQUIRED_KEYS = ["intrinsic_params", "image_resolution"]
INTRINSIC_PARAMS_REQUIRED_KEYS = ["fx", "fy", "cx", "cy"]

# 检测阈值
DETECTION_CONFIDENCE_THRESHOLD = 0.7
DEPTH_VALIDATION_THRESHOLD = 0.1
COORDINATE_QUALITY_THRESHOLD = 0.8
MAX_PROCESSING_TIME = 0.1  # 秒
