# 统一配置管理

CAMERA_PARAMS_PATH = "project/config/camera_params.json"


MAX_RECOGNITION_THREADS = 1

MAX_FITTING_THREADS = 4

MAX_TRACKING_THREADS = 1

MAX_THREAD_MANAGER_THREADS = 1

MAX_THREADS = MAX_RECOGNITION_THREADS + MAX_FITTING_THREADS + MAX_TRACKING_THREADS + MAX_THREAD_MANAGER_THREADS

# Frame ID 管理配置
FRAME_ID_PERIOD_SECONDS = 10.0  # 周期（秒），每个周期清空半个周期的数据
FRAME_ID_CLEANUP_ENABLED = True  # 是否启用自动清理

# 桥接层配置（WebSocket，供 Node.js / Unity 等前端连接）
BRIDGE_ENABLED = True  # 为 True 时启动桥接服务
BRIDGE_HOST = "0.0.0.0"
BRIDGE_PORT = 8765